[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps = 
	m5stack/M5Unified @ ^0.1.14
	m5stack/M5GFX @ ^0.1.14
build_src_filter = +<*.cpp>
extra_scripts = post:copy_assets.py

[env:emulator_macos]
platform = native
build_type = debug
build_flags =
    -std=gnu++14
    -DLGFX_USE_SDL
    -DSDKCONFIG=\"sdkconfig.h\"
    ; Force the compiler to use the SDL2 graphics driver instead of SPI hardware
    !pkg-config --cflags --libs sdl2
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
lib_compat_mode = off
extra_scripts = post:copy_assets.py