[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps = 
	m5stack/M5Unified @ ^0.2.14
	m5stack/M5GFX @ ^0.2.20
	bblanchon/ArduinoJson @ ^7.0.4
	m5stack/M5Cardputer @ ^1.0.3
	earlephilhower/ESP8266Audio @ ^1.9.7
build_src_filter = +<*.cpp>
extra_scripts = post:copy_assets.py
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

[env:emulator_macos]
platform = native
build_type = debug
build_flags =
    -std=gnu++14
    -DLGFX_USE_SDL
    -DSDKCONFIG=\"sdkconfig.h\"
    -DM5GFX_BOARD=m5gfx::board_M5Cardputer
    -DM5GFX_SCALE=2
    ; Force the compiler to use the SDL2 graphics driver instead of SPI hardware
    !pkg-config --cflags --libs sdl2
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    bblanchon/ArduinoJson @ ^7.0.4
lib_compat_mode = off
extra_scripts = post:copy_assets.py
board_build.filesystem = littlefs